# .github/workflows/main.yaml
# ------------------------------
# CI/CD Pipeline for Python app without Docker
# ------------------------------

name: Python CI/CD Pipeline (No Docker)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: pytest

      - name: Deploy to EC2 via SSH
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/github-actions-python-demo || exit
            git pull origin main
            pkill -f "python app.py" || true
            python3 -m pip install -r requirements.txt
            nohup python3 app.py > app.log 2>&1 &
