name: CI/CD Pipeline - Flask App

# Trigger workflow on push to main branch
on:
  [push]:
    branches:
      - main  

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Step 3: Install dependencies in a virtual environment
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run unit tests
    - name: Run tests
      run: |
        source venv/bin/activate
        pytest test_app.py

    # Step 5: Deploy to EC2 via SSH
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/github-actions-python-demo
          git pull origin main
          # Create or activate virtual environment
          source venv/bin/activate || python3 -m venv venv && source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          # Stop running app if any and restart
          pkill -f app.py || true
          nohup python3 app.py > app.log 2>&1 &
