name: CI/CD Pipeline - Flask App

on:
  push:
    branches:
      - main   # Runs whenever you push to main branch

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    # Step 4: Run tests
    - name: Run unit tests
      run: |
        source venv/bin/activate
        pytest test_app.py

    # Step 5: Deploy to EC2 via SSH
    - name: Deploy to EC2 instance
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/github-actions-python-demo
          git pull origin main
          source venv/bin/activate || python3 -m venv venv && source venv/bin/activate
          pip install -r requirements.txt
          nohup python3 app.py > app.log 2>&1 &
