name: Build, Test, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Step 4: Run unit tests
      - name: Run unit tests
        run: |
          pytest tests/  # Use pytest instead of unittest for better CI compatibility

      # Step 5: Await manual approval before deployment
      - name: Await manual approval
        uses: trstringer/manual-approval@v1
        with:
          approvers: ${{ secrets.DEPLOY_APPROVER }}
          secret: ${{ github.TOKEN }}
          issue-title: "Deploy approval needed"
          issue-body: "Please approve deployment to production."

      # Step 6: Deploy application (only runs if tests pass and approval given)
      - name: Deploy application
        if: ${{ success() }}
        run: |
          echo "Deploying application..."
          # Example deployment command:
          # ssh -o StrictHostKeyChecking=no ubuntu@<EC2_IP> 'bash deploy.sh'
