name: Build, Test, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          source venv/bin/activate
          python -m unittest discover -s tests

      - name: Await manual approval
        uses: trstringer/manual-approval@v1
        with:
          approvers: raafiya-gouher   # 👈 Replace with your GitHub username
          secret: ${{ github.TOKEN }}
          issue-title: "Deploy approval needed"
          issue-body: "Please approve deployment to production."

      - name: Deploy application
        if: ${{ success() }}
        run: |
          echo "Deploying application..."
          # Example: SSH into EC2 and deploy
          # ssh -o StrictHostKeyChecking=no ubuntu@<EC2_IP> 'bash deploy.sh'
