name: Build, Test, and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write  

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Step 4: Run unit tests
      - name: Run unit tests
        run: |
          PYTHONPATH=$(pwd) pytest tests/ 

      # Step 5: Await manual approval before deployment
      - name: Await manual approval
        uses: trstringer/manual-approval@v1
        with:
          approvers: ${{ secrets.DEPLOY_APPROVER }}
          secret: ${{ github.TOKEN }}
          issue-title: "Deploy approval needed"
          issue-body: "Please approve deployment to production."

      # Step 6: Deploy application (only if tests pass and approval is given)
      - name: Deploy to EC2
        if: ${{ success() }}
        env:
          EC2_IP: ${{ secrets.EC2_HOST }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "Deploying to EC2..."
          echo "$EC2_SSH_KEY" > ec2-key.pem
          chmod 600 ec2-key.pem

          # Copy application files
          scp -o StrictHostKeyChecking=no -i ec2-key.pem app.py ubuntu@$EC2_IP:/home/ubuntu/

          # Restart the app on EC2
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ubuntu@$EC2_IP << 'EOF'
            pkill -f app.py || true
            nohup python3 /home/ubuntu/app.py > /home/ubuntu/app.log 2>&1 &
          EOF
